# Generated by Django 5.2.7 on 2025-10-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_item_unit_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('group', 'name')},
        ),
    ]
